#cloud-config
# ============================================================================
# Purple Computer Autoinstall Configuration
# ============================================================================
#
# PURPOSE: This file tells Ubuntu's installer WHAT to do during installation
#
# When the ISO boots, Ubuntu's subiquity installer reads this file and:
# - Partitions the disk
# - Installs packages (from bundled pool or internet)
# - Creates users and configures the system
# - Runs setup scripts
#
# This file is the SINGLE SOURCE OF TRUTH for:
# - Package list (build-iso.sh extracts packages from here using yq)
# - User configuration
# - System setup
#
# IMPORTANT: The package list below is automatically extracted by build-iso.sh
# to download packages for offline installation. Keep packages in sync by only
# editing the packages list in this file, never in build-iso.sh.
#
# Architecture: Ubuntu Server + minimal Xorg (no desktop environment) + alacritty fullscreen
# No GUI, no window manager, no desktop bloat - just a fullscreen terminal
# ============================================================================

autoinstall:
  version: 1

  # Reporting - silence verbose installer output
  reporting:
    builtin:
      type: print

  # Early commands run before installation begins
  early-commands:
    # Redirect kernel/installer messages away from main console
    - echo 3 > /proc/sys/kernel/printk
    # Show friendly welcome message
    - echo -e "\n\n"
    - echo -e "\033[1;35m"
    - echo "  ╔════════════════════════════════════════╗"
    - echo "  ║                                        ║"
    - echo "  ║       Welcome to Purple Computer!     ║"
    - echo "  ║                                        ║"
    - echo "  ╚════════════════════════════════════════╝"
    - echo -e "\033[0m"
    - echo ""
    - echo "  Setting up your computer..."
    - echo "  This will take about 5 minutes."
    - echo ""

  # Locale and keyboard settings
  locale: en_US.UTF-8
  keyboard:
    layout: us

  # Network configuration - DISABLED for offline install
  # All packages are bundled in the ISO
  network:
    version: 2

  # Storage configuration - use entire disk
  storage:
    layout:
      name: lvm
      sizing-policy: all

  # Curtin configuration - reduce verbosity
  curtin:
    install:
      log_file: /var/log/curtin-install.log
      error_tarfile: /var/log/curtin-errors.tar
      save_install_config: false
      save_install_log: false

  # Identity - creates the purple user
  # NOTE: User will have NO PASSWORD (account is locked, auto-login only)
  # Parent mode is protected by a separate parent password set on first use
  identity:
    hostname: purplecomputer
    username: purple
    password: "$6$locked$locked"
    # Password is locked - no login via password possible
    # System uses auto-login on TTY1
    # Parent mode uses separate password stored in ~/.purple/parent.json

  # SSH disabled for security
  ssh:
    install-server: false

  # Package selection
  # IMPORTANT: Ubuntu Server base, NO desktop environment packages
  packages:
    # X11 minimal (just the X server, no window manager, no desktop environment)
    - xorg
    - xinit
    - xserver-xorg-video-all
    - matchbox-window-manager

    # Terminal emulator (runs fullscreen via xinitrc)
    - alacritty

    # Python environment
    - python3
    - python3-pip
    - python3-venv

    # Text-to-speech
    - espeak-ng

    # Audio
    - alsa-utils
    - pulseaudio

    # Fonts and emoji
    - fonts-noto
    - fonts-noto-color-emoji

    # Utilities
    - git
    - curl
    - wget
    - vim
    - less

    # WiFi tools
    - wpasupplicant
    - wireless-tools
    - iw
    - rfkill

  # Disable automatic updates for stability
  updates: security

  # Late commands - run after installation, before reboot
  late-commands:
    - echo ""
    - echo -e "\033[1;35m  ✓\033[0m Installation complete"
    - echo ""
    - echo "  Configuring Purple Computer..."
    - echo ""

    # Lock the purple user account (no password login)
    - chroot /target passwd -l purple

    # Create Purple Computer directory structure
    - mkdir -p /target/home/purple/.purple/modes
    - mkdir -p /target/home/purple/.purple/packs
    - mkdir -p /target/home/purple/.config/alacritty
    - mkdir -p /target/usr/share/purple

    # Set ownership
    - chroot /target chown purple:purple /home/purple
    - chroot /target chown -R purple:purple /home/purple/.purple
    - chroot /target chown -R purple:purple /home/purple/.config

    # Disable unnecessary services
    - chroot /target systemctl disable systemd-networkd-wait-online.service
    - chroot /target systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

    # Configure audio
    - chroot /target usermod -a -G audio purple

    # Final message
    - echo "Purple Computer installation complete!"

    # Restore Ubuntu repos for future updates (after offline install)
    - |
      cat > /target/etc/apt/sources.list <<'SOURCES'
      # Ubuntu 24.04 LTS (Noble Numbat)
      deb http://archive.ubuntu.com/ubuntu noble main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu noble-security main restricted universe multiverse
      SOURCES

    # Copy Purple Computer files from ISO to target system
    - mkdir -p /target/opt/purple-install
    - cp -r /cdrom/purple_files/* /target/opt/purple-install/

    # Setup getty auto-login NOW (before first boot) so it works immediately
    - mkdir -p /target/etc/systemd/system/getty@tty1.service.d
    - |
      cat > /target/etc/systemd/system/getty@tty1.service.d/override.conf <<'GETTY'
      # Getty Auto-Login Override for Purple Computer
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin purple --noclear %I $TERM
      StandardInput=tty
      StandardOutput=tty
      GETTY

    # Create first-boot setup service (blocks getty until setup completes)
    - |
      cat > /target/etc/systemd/system/purple-first-boot.service <<'EOF'
      [Unit]
      Description=Purple Computer First Boot Setup
      After=systemd-user-sessions.service
      Before=getty@tty1.service
      ConditionPathExists=!/etc/purple-computer-configured
      DefaultDependencies=no

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/local/bin/purple-first-boot.sh
      StandardOutput=journal+console
      StandardError=journal+console

      [Install]
      WantedBy=multi-user.target
      EOF

    # Create first-boot setup script (embeds all configs inline)
    - |
      cat > /target/usr/local/bin/purple-first-boot.sh <<'FIRSTBOOT'
      #!/bin/bash
      set -e

      echo ""
      echo "=========================================="
      echo "  Purple Computer First Boot Setup"
      echo "=========================================="
      echo ""
      echo "Setting up Purple Computer for the first time..."
      echo "This will take about 30 seconds."
      echo ""

      # Copy Purple TUI from pre-installed location (bundled in ISO)
      echo "Installing Purple Computer files..."
      mkdir -p /home/purple/.purple
      if [ -d /opt/purple-install ]; then
        cp -r /opt/purple-install/* /home/purple/.purple/
        echo "✓ Files installed from ISO"
      else
        echo "ERROR: Purple Computer files not found at /opt/purple-install"
        echo "The ISO may be corrupted. Please re-download and try again."
        echo ""
        echo "Press Enter to get a login prompt..."
        read
        exit 1
      fi
      if id purple >/dev/null 2>&1; then
        chown -R purple:purple /home/purple/.purple
      fi
      find /home/purple/.purple -name "*.py" -type f -exec chmod +x {} \;

      echo "✓ Installation complete"
      echo ""

      # Getty auto-login is already configured in late-commands
      # Just ensure it's enabled
      echo "Configuring auto-login..."
      systemctl daemon-reload
      systemctl enable getty@tty1.service
      echo "✓ Auto-login configured"
      echo ""

      # Create xinitrc (embed inline)
      echo "Setting up X11 environment..."
      cat > /home/purple/.xinitrc <<'XINITRC'
      #!/bin/bash
      # Purple Computer X11 Startup
      xset s off
      xset -dpms
      xset s noblank
      xset b off
      xset r rate 300 30
      xsetroot -solid "#2d1b4e"
      matchbox-window-manager &

      # Dev mode: Use /mnt/purple if mounted (for VM development)
      # Production: Use /home/purple/.purple (for standalone installations)
      if [ -d /mnt/purple/purple_tui ] && [ -f /mnt/purple/purple_tui/purple_tui.py ]; then
          PURPLE_PATH="/mnt/purple/purple_tui/purple_tui.py"
      else
          PURPLE_PATH="/home/purple/.purple/purple_tui.py"
      fi

      exec alacritty --config-file /home/purple/.config/alacritty/alacritty.toml \
          -e "$PURPLE_PATH"
      XINITRC

      if id purple >/dev/null 2>&1; then
        chown purple:purple /home/purple/.xinitrc
        chmod +x /home/purple/.xinitrc
      fi


      # Create alacritty config (embed inline)
      mkdir -p /home/purple/.config/alacritty
      cat > /home/purple/.config/alacritty/alacritty.toml <<'ALACRITTY'
      # Purple Computer Alacritty Configuration
      [window]
      decorations = "None"
      startup_mode = "Fullscreen"
      opacity = 1.0

      [font]
      size = 22.0

      [font.normal]
      family = "JetBrainsMono Nerd Font"
      style = "Regular"

      [colors.primary]
      background = "#2d1b4e"
      foreground = "#f5f3ff"

      [colors.cursor]
      text = "#2d1b4e"
      cursor = "#c4b5fd"

      [colors.normal]
      black = "#1e0a3c"
      red = "#ff6b9d"
      green = "#a0d995"
      yellow = "#ffd97d"
      blue = "#9bb3ff"
      magenta = "#e0b0ff"
      cyan = "#a8e6e1"
      white = "#f5f3ff"

      [cursor]
      style = "Beam"

      [bell]
      duration = 0

      [terminal]
      osc52 = "Disabled"
      ALACRITTY

      if id purple >/dev/null 2>&1; then
        chown -R purple:purple /home/purple/.config
      fi


      # Setup auto-startx in .bash_profile
      echo "Configuring auto-start..."
      cat >> /home/purple/.bash_profile <<'BASHEOF'
      # Purple Computer auto-start X11
      if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = "1" ]; then
        exec startx
      fi
      BASHEOF
      if id purple >/dev/null 2>&1; then
        chown purple:purple /home/purple/.bash_profile
      fi

      echo "✓ Auto-start configured"
      echo ""

      echo "✓ Xorg environment configured"
      echo ""

      # Mac hardware support - load hid-apple for keyboards/trackpads
      echo "Configuring Mac hardware support..."
      if lsmod | grep -q hid_apple || modinfo hid_apple >/dev/null 2>&1; then
        echo "hid_apple" >> /etc/modules
        # Enable function keys as standard F1-F12 by default
        echo "options hid_apple fnmode=2" > /etc/modprobe.d/hid_apple.conf
        echo "✓ Mac keyboard/trackpad support enabled"
      fi
      echo ""

      # Final ownership fix (CRITICAL for .Xauthority and X11 logs)
      echo "Finalizing setup..."
      # Fix home directories themselves first (prevents X11 permission errors)
      if id purple >/dev/null 2>&1; then
        chown purple:purple /home/purple
        chown -R purple:purple /home/purple
      fi

      # Clean up staging area
      rm -rf /opt/purple-install

      # Mark as configured and disable this service
      touch /etc/purple-computer-configured
      systemctl disable purple-first-boot.service

      echo "✓ Setup complete"
      echo ""
      echo "=========================================="
      echo "  Purple Computer is ready!"
      echo "=========================================="
      echo ""
      echo "Starting Purple Computer..."
      sleep 2
      FIRSTBOOT

    - chmod +x /target/usr/local/bin/purple-first-boot.sh
    - chroot /target systemctl enable purple-first-boot.service

    # Set GRUB timeout to 0 for fast boot
    - curtin in-target --target=/target -- sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/' /etc/default/grub
    - curtin in-target --target=/target -- update-grub

    - echo "Purple Computer late commands complete!"

  # Automatically reboot after installation
  shutdown: reboot
