"""
Content API for Purple Computer

Provides a stable interface for modes to access content from purplepacks:
- Emojis (with synonyms)
- Stories (text + audio)
- Sounds (audio files)

Purplepacks are content-only (JSON + assets) - NO executable Python code.
"""

import json
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Optional


@dataclass
class Resolution:
    """Result of resolving a bare word: an emoji glyph or a color hex, or nothing.

    kind is "emoji", "color", or None. correction is (typed, matched) when a
    fuzzy match fired, else None.
    """
    kind: Optional[str]
    value: Optional[str]
    correction: Optional[tuple[str, str]] = None


# Precomputed plural/singular lookup tables for Purple's closed vocabulary
# (emoji keys, color names, synonyms, ranked words). Generated by
# scripts/build_plural_tables.py. We used to call `inflect` at runtime,
# but its import cost ~1.4s on dev and ~8-12s on slow laptops due to
# typeguard AST rewriting. See guides/boot-hang-debugging.md.
@cache
def _plural_tables() -> tuple[dict[str, str], dict[str, str]]:
    path = Path(__file__).parent / "plural_forms.json"
    with path.open() as f:
        data = json.load(f)
    return data["singular_to_plural"], data["plural_to_singular"]


def singularize(word: str) -> str | None:
    """Return the singular form of a known plural, or None.

    Only recognises words in Purple's closed vocabulary (emoji/color/rankings).
    Unknown words or non-plurals return None — matching the previous inflect
    behaviour that `singular_noun` returned False for non-plurals.
    """
    _, plural_to_singular = _plural_tables()
    return plural_to_singular.get(word.lower())


def pluralize(word: str) -> str:
    """Return the plural form of a known singular.

    Falls back to appending 's' for words outside the precomputed vocabulary
    (preserves the autocomplete-index behaviour of always producing some plural).
    """
    singular_to_plural, _ = _plural_tables()
    lower = word.lower()
    return singular_to_plural.get(lower, lower + "s")


class ContentManager:
    """
    Manages loading and accessing content from purplepacks.

    Purplepacks are stored in ~/.purple/packs/ and contain:
    - manifest.json (pack metadata)
    - content/ directory with JSON and asset files
    """

    def __init__(self, packs_dir: Optional[Path] = None):
        self.packs_dir = packs_dir or Path.home() / ".purple" / "packs"
        self.emojis: dict[str, str] = {}           # word -> emoji
        self.colors: dict[str, str] = {}           # color name -> hex code
        self.sounds: dict[str, Path] = {}          # sound_id -> file path
        self._loaded = False
        # Unified prefix index: prefix -> [(word, color_hex|None, emoji|None), ...]
        # Ranked by kid-likelihood from rankings.txt
        self._word_prefix_index: dict[str, list[tuple[str, str | None, str | None]]] = {}
        # Fuzzy match correction tracking (set when fuzzy fallback fires)
        self._last_correction: tuple[str, str] | None = None

    def load_all(self) -> None:
        """Load content from all installed packs"""
        if self._loaded:
            return

        # Load built-in defaults (colors only, emoji come from packs)
        self._load_defaults()

        # Load from source-relative packs dir (works in dev and production)
        source_packs = Path(__file__).parent.parent / "packs"
        if source_packs.exists():
            for pack_dir in source_packs.iterdir():
                if pack_dir.is_dir():
                    self._load_pack(pack_dir)

        # Then load from user-installed packs (can override/extend)
        if self.packs_dir.exists():
            for pack_dir in self.packs_dir.iterdir():
                if pack_dir.is_dir():
                    self._load_pack(pack_dir)

        self._loaded = True
        self._build_prefix_indexes()

    def _load_defaults(self) -> None:
        """Load default colors. Emoji come from the core-emoji pack."""
        self.emojis = {}

        # Default colors for paint mixing (RYB primary/secondary + common colors)
        self.colors = {
            # Primary colors (paint)
            "red": "#ED1C24",      # Crayola red (classic fire-engine red)
            "yellow": "#FFEB00",   # Primary yellow
            "blue": "#1F75FE",     # Crayola blue (bright, clearly blue)

            # Secondary colors (what you get from mixing primaries)
            "orange": "#FF6600",   # Red + Yellow
            "green": "#48D370",    # What you get from mixing yellow + blue
            "purple": "#7B2D8E",   # Red + Blue
            "violet": "#7B2D8E",   # Same as purple

            # Tertiary and common colors
            "pink": "#FF69B4",
            "brown": "#8B4513",
            "black": "#1A1A1A",
            "white": "#F5F5F5",
            "gray": "#808080",
            "grey": "#808080",

            # Fun colors kids know
            "cyan": "#00FFFF",
            "magenta": "#FF00FF",
            "gold": "#FFD700",
            "silver": "#C0C0C0",
            "teal": "#008080",
            "turquoise": "#40E0D0",
            "coral": "#FF7F50",
            "salmon": "#FA8072",
            "peach": "#FFCBA4",
            "lavender": "#E6E6FA",
            "mint": "#98FF98",
            "lime": "#32CD32",
            "maroon": "#800000",
            "navy": "#000080",
            "olive": "#808000",
            "indigo": "#4B0082",
            "tan": "#D2B48C",
            "beige": "#F5F5DC",
            "cream": "#FFFDD0",
            "sky": "#87CEEB",
            "rose": "#FF007F",
            "crimson": "#DC143C",
            "scarlet": "#FF2400",

            # More fun one-word colors
            "periwinkle": "#CCCCFF",
            "lilac": "#C8A2C8",
            "plum": "#8E4585",
            "orchid": "#DA70D6",
            "fuchsia": "#FF00FF",
            "mauve": "#E0B0FF",
            "ruby": "#E0115F",
            "emerald": "#50C878",
            "sapphire": "#0F52BA",
            "amber": "#FFBF00",
            "copper": "#B87333",
            "bronze": "#CD7F32",
            "ivory": "#FFFFF0",
            "aqua": "#00FFFF",
            "azure": "#007FFF",
            "cerulean": "#2A52BE",
            "cobalt": "#0047AB",
            "chartreuse": "#7FFF00",
            "khaki": "#C3B091",
            "burgundy": "#800020",
            "mulberry": "#C54B8C",
            "raspberry": "#E30B5C",
            "tangerine": "#FF9966",
            "apricot": "#FBCEB1",
            "lemon": "#FFF44F",
            "canary": "#FFEF00",
            "sunshine": "#FFFD37",
            "daffodil": "#FFFF31",
            "buttercup": "#F9E81E",
            "honey": "#EB9605",
            "mustard": "#FFDB58",
            "sepia": "#704214",
            "chocolate": "#7B3F00",
            "chestnut": "#954535",
            "cinnamon": "#D2691E",
            "ginger": "#B06500",
            "caramel": "#FFD59A",
            "rust": "#B7410E",
            "brick": "#CB4154",
            "bubblegum": "#FFC1CC",
            "blush": "#DE5D83",
            "hotpink": "#FF69B4",
            "carnation": "#FFA6C9",
            "spearmint": "#45B08C",
            "jade": "#00A86B",
            "moss": "#8A9A5B",
            "sage": "#9DC183",
            "pistachio": "#93C572",
            "cornflower": "#6495ED",
            "slate": "#708090",
            "eggplant": "#614051",
            "amethyst": "#9966CC",
            "iris": "#5A4FCF",
            "wisteria": "#C9A0DC",
            "heather": "#B7A2C7",
        }

    def _load_pack(self, pack_dir: Path) -> None:
        """Load content from a single pack directory"""
        manifest_path = pack_dir / "manifest.json"
        if not manifest_path.exists():
            return

        try:
            with open(manifest_path) as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            return

        pack_type = manifest.get("type", "")
        content_dir = pack_dir / "content"

        if pack_type == "emoji":
            self._load_emoji_pack(content_dir)
        elif pack_type == "sounds":
            self._load_sounds_pack(content_dir, pack_dir)

    def _load_emoji_pack(self, content_dir: Path) -> None:
        """Load emoji pack: primary emoji and synonyms"""
        emoji_file = content_dir / "emoji.json"
        if emoji_file.exists():
            try:
                with open(emoji_file) as f:
                    data = json.load(f)
                    self.emojis.update(data)
            except (json.JSONDecodeError, OSError):
                pass

        # Load synonyms (alias -> primary word, resolved to emoji)
        synonyms_file = content_dir / "synonyms.json"
        if synonyms_file.exists():
            try:
                with open(synonyms_file) as f:
                    synonyms = json.load(f)
                    for alias, target in synonyms.items():
                        if target in self.emojis:
                            self.emojis[alias] = self.emojis[target]
            except (json.JSONDecodeError, OSError):
                pass

    def _load_sounds_pack(self, content_dir: Path, pack_dir: Path) -> None:
        """Load sound file references from pack"""
        sounds_file = content_dir / "sounds.json"
        if sounds_file.exists():
            try:
                with open(sounds_file) as f:
                    data = json.load(f)
                    for sound_id, filename in data.items():
                        sound_path = pack_dir / "assets" / filename
                        if sound_path.exists():
                            self.sounds[sound_id] = sound_path
            except (json.JSONDecodeError, OSError):
                pass

    # Public API for modes

    def exact_emoji(self, word: str) -> Optional[str]:
        """Emoji for a word by exact or singular/plural match only (no fuzzy)."""
        word = word.lower().strip()
        if emoji := self.emojis.get(word):
            return emoji
        if (singular := singularize(word)) and (emoji := self.emojis.get(singular)):
            return emoji
        return None

    def _fuzzy_lookup(self, word: str, table: dict[str, str]) -> Optional[str]:
        """Fuzzy match a word against table keys and their plural forms.

        Keys come before plurals in the candidate list so a singular match
        wins ties (existing corrections never change; only misses can become
        plural matches). Plurals map back to their source key explicitly:
        singularize() can't reverse fallback plurals of words outside the
        precomputed tables (e.g. from user packs).
        """
        from .fuzzy import fuzzy_match
        word = word.lower().strip()
        forms = {k: k for k in table}
        for k in table:
            forms.setdefault(pluralize(k), k)
        if match := fuzzy_match(word, list(forms)):
            self._last_correction = (word, match)
            return table[forms[match]]
        return None

    def fuzzy_emoji(self, word: str) -> Optional[str]:
        """Emoji for a word by fuzzy match only (DL distance, min 5 chars).

        Records the correction so callers can surface it. The emoji dict is
        large (400+), so the min-5 floor avoids 3-4 char keymash collisions.
        Plural typos match too ("doggiess" corrects to "doggies").
        """
        return self._fuzzy_lookup(word, self.emojis)

    def get_emoji(self, word: str) -> Optional[str]:
        """Get emoji for a word: exact/singular, then fuzzy (DL distance, min 5)."""
        return self.exact_emoji(word) or self.fuzzy_emoji(word)

    def emoji_to_word(self, emoji: str) -> Optional[str]:
        """Reverse lookup: get word for an emoji character"""
        for word, e in self.emojis.items():
            if e == emoji:
                return word
        return None

    def get_sound(self, sound_id: str) -> Optional[Path]:
        """Get path to a sound file"""
        return self.sounds.get(sound_id)

    def list_emojis(self) -> list[str]:
        """Get list of all available emoji words"""
        return sorted(self.emojis.keys())

    def _load_rankings(self) -> dict[str, int]:
        """Load word rankings from rankings.txt files in packs.

        Returns {word: rank} where lower rank = higher priority.
        """
        rankings: dict[str, int] = {}
        rank = 0
        # Check source-relative packs first, then user packs
        for packs_dir in [Path(__file__).parent.parent / "packs", self.packs_dir]:
            if not packs_dir.exists():
                continue
            for pack_dir in packs_dir.iterdir():
                rankings_file = pack_dir / "content" / "rankings.txt"
                if not rankings_file.exists():
                    continue
                try:
                    for line in rankings_file.read_text().splitlines():
                        line = line.strip()
                        if line and not line.startswith("#"):
                            if line not in rankings:
                                rankings[line] = rank
                                rank += 1
                except OSError:
                    pass
        return rankings

    def _build_prefix_indexes(self) -> None:
        """Build unified prefix index for instant autocomplete.

        Called once at load time. Merges emojis and colors into a single index,
        ranked by kid-likelihood from rankings.txt.
        """
        rankings = self._load_rankings()
        unranked = len(rankings)

        # prefix -> {word: (color_hex|None, emoji|None)}
        by_prefix: dict[str, dict[str, tuple[str | None, str | None]]] = {}

        def _add_word(word: str, color: str | None, emoji: str | None) -> None:
            plural = pluralize(word)
            for form in [word, plural]:
                for i in range(2, len(form) + 1):
                    p = form[:i]
                    bucket = by_prefix.setdefault(p, {})
                    if form in bucket:
                        # Merge: word can be both a color and an emoji
                        old_color, old_emoji = bucket[form]
                        bucket[form] = (color or old_color, emoji or old_emoji)
                    else:
                        bucket[form] = (color, emoji)

        for word, emoji in self.emojis.items():
            _add_word(word, None, emoji)

        for name, hex_code in self.colors.items():
            _add_word(name, hex_code, None)

        # Sort by rank, then dedup: keep the best-ranked word for each emoji/color
        def _dedup(entries: list[tuple[str, str | None, str | None]]):
            seen_emojis: set[str] = set()
            seen_colors: set[str] = set()
            result = []
            for w, c, e in entries:
                if e and e in seen_emojis:
                    continue
                if c and not e and c in seen_colors:
                    continue
                if e:
                    seen_emojis.add(e)
                if c:
                    seen_colors.add(c)
                result.append((w, c, e))
            return result

        self._word_prefix_index = {
            p: _dedup(sorted(
                [(w, c, e) for w, (c, e) in entries.items()],
                key=lambda x: rankings.get(x[0], unranked),
            ))
            for p, entries in by_prefix.items()
        }

    def search_words(self, prefix: str) -> list[tuple[str, str | None, str | None]]:
        """Search for words starting with prefix, returns [(word, color_hex|None, emoji|None), ...].

        Unified ranked search across emojis and colors.
        """
        return self._word_prefix_index.get(prefix.lower(), [])

    def search_emojis(self, prefix: str) -> list[tuple[str, str]]:
        """Search for emojis starting with prefix, returns [(word, emoji), ...]."""
        return [
            (w, e) for w, _c, e in self.search_words(prefix) if e is not None
        ]

    def exact_color(self, word: str) -> Optional[str]:
        """Hex color for a name by exact or singular/plural match only (no fuzzy)."""
        word = word.lower().strip()
        if color := self.colors.get(word):
            return color
        if (singular := singularize(word)) and (color := self.colors.get(singular)):
            return color
        return None

    def fuzzy_color(self, word: str) -> Optional[str]:
        """Hex color for a name by fuzzy match only (DL distance, min 5 chars).

        Records the correction. Min 5 chars: shorter floors are unsafe even
        though the color dict is small, because common English words collide
        with short color names at distance 1 (e.g. "tell"->"teal"). Forgiveness
        for short slips like "bleu" lives in the explicit `color X` command
        (loose match) and in autocomplete, not in bare-word resolution.
        """
        return self._fuzzy_lookup(word, self.colors)

    def get_color(self, word: str) -> Optional[str]:
        """Get hex color: exact/singular, then fuzzy (DL distance, min 4)."""
        return self.exact_color(word) or self.fuzzy_color(word)

    def resolve(self, word: str) -> Resolution:
        """Classify a bare word, exact-first across both dictionaries.

        Order: exact emoji → exact color → fuzzy emoji → fuzzy color. An exact
        match in either dictionary always beats a fuzzy match in the other, so
        "white" (exact color) is never hijacked by fuzzy emoji "write". This is
        the standalone classifier; contextual grammar (color mixing, count +
        noun) still calls the category-specific lookups directly.
        """
        if e := self.exact_emoji(word):
            return Resolution("emoji", e)
        if c := self.exact_color(word):
            return Resolution("color", c)
        if e := self.fuzzy_emoji(word):
            return Resolution("emoji", e, self._last_correction)
        if c := self.fuzzy_color(word):
            return Resolution("color", c, self._last_correction)
        return Resolution(None, None)

    def pop_correction(self) -> tuple[str, str] | None:
        """Retrieve and clear the last fuzzy correction, if any."""
        c = self._last_correction
        self._last_correction = None
        return c

    def get_modified_color(self, text: str) -> tuple[str, str, list[str], str] | None:
        """Parse adjective(s) + color name, e.g. 'bright green', 'dark light blue'.

        Returns (modified_hex, base_hex, adjectives, color_name) or None.
        Adjectives are applied left to right.
        """
        from .color_mixing import COLOR_ADJECTIVES, modify_color

        words = text.lower().strip().split()
        if len(words) < 2:
            return None

        # Collect leading adjectives, rest is the color name
        adjectives = []
        for i, w in enumerate(words):
            if w in COLOR_ADJECTIVES:
                adjectives.append(w)
            else:
                break
        else:
            return None  # All words were adjectives, no color

        if not adjectives:
            return None

        color_name = " ".join(words[len(adjectives):])
        base_hex = self.get_color(color_name)
        if not base_hex:
            return None

        # Apply adjectives left to right
        modified = base_hex
        for adj in adjectives:
            modified = modify_color(modified, adj)

        return (modified, base_hex, adjectives, color_name)

    def search_colors(self, prefix: str) -> list[tuple[str, str]]:
        """Search for colors starting with prefix, returns [(name, hex), ...]."""
        return [
            (w, c) for w, c, _e in self.search_words(prefix) if c is not None
        ]

    def list_colors(self) -> list[str]:
        """Get list of all available color names"""
        return sorted(self.colors.keys())

    def get_word(self, word: str) -> tuple[str, str] | None:
        """Get emoji or color for a word, including plural forms.

        Returns (value, type) where type is 'emoji' or 'color', or None if not found.
        For plurals like 'tomatoes', 'cherries', 'wolves', returns the emoji/color.
        """
        word = word.lower().strip()

        # Check emoji first (get_emoji handles plurals via singularize)
        emoji = self.get_emoji(word)
        if emoji:
            return (emoji, "emoji")

        # Check color (get_color handles plurals via singularize)
        color = self.get_color(word)
        if color:
            return (color, "color")

        return None

    def is_valid_word(self, word: str) -> bool:
        """Check if word is a valid emoji or color, including plural forms."""
        return self.get_word(word) is not None

    def is_exact_word(self, word: str) -> bool:
        """Exact emoji or color word, singular or plural. Fuzzy matches don't
        count: a typo must stay correctable to a command or operator."""
        return bool(self.exact_emoji(word) or self.exact_color(word))


# Global content manager instance
_content: Optional[ContentManager] = None


def get_content() -> ContentManager:
    """Get the global content manager"""
    global _content
    if _content is None:
        _content = ContentManager()
        _content.load_all()
    return _content
