"""AI-generated Play Mode composition: Digital Smiley Face

Generated by: python tools/play_ai.py "make a smiley face pattern with all the colors" --save tune
"""

from ..script import PlayKeys, Comment, Pause, SwitchMode

SEGMENT = [
    SwitchMode("play"),
    Pause(0.3),

    Comment("=== Eyes (purple, 1 press each) - cheerful high notes ==="),
    PlayKeys(
        sequence=['4', None, None, '7'],
        tempo_bpm=120,
        pause_after=0.5,
    ),

    Comment("=== Nose (blue, 2 presses each) - middle harmony ==="),
    PlayKeys(
        sequence=['t', 't', None, 'y', 'y'],
        tempo_bpm=100,
        pause_after=0.6,
    ),

    Comment("=== Smile corners (red, 3 presses each) - rhythmic foundation ==="),
    PlayKeys(
        sequence=['d', 'd', 'd', None, None, 'k', 'k', 'k'],
        tempo_bpm=140,
        pause_after=0.4,
    ),

    Comment("=== Smile bottom (red, 3 presses each) - ascending melody ==="),
    PlayKeys(
        sequence=['v', 'v', 'v', 'b', 'b', 'b', 'n', 'n', 'n', 'm', 'm', 'm'],
        tempo_bpm=160,
        pause_after=0.3,
    ),

    Pause(2.0),
    Comment("AI-generated composition complete!"),
]
