"""AI-generated drawing demo."""

from purple_tui.demo.script import (
    PressKey, SwitchMode, Pause, DrawPath, MoveSequence, Comment,
)

AI_DRAWING = [
    Comment("=== AI GENERATED DRAWING ==="),
    SwitchMode("doodle"),
    Pause(0.3),
    PressKey("tab"),  # Enter paint mode

    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    MoveSequence(directions=['left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    PressKey('t'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('y'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['right', 'up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['up', 'up'], delay_per_step=0.008),
    PressKey('r'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('.'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up', 'up', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'down'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('.'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'up'], delay_per_step=0.008),
    PressKey('.'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'down', 'down'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('.'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['up'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['down'], delay_per_step=0.008),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up', 'up', 'up', 'up', 'up', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'down'], delay_per_step=0.008),
    PressKey('z'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('.'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'up'], delay_per_step=0.008),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    PressKey('f'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down'], delay_per_step=0.008),
    PressKey('s'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'], delay_per_step=0.008),
    PressKey('s'),
    MoveSequence(directions=['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'], delay_per_step=0.008),
    PressKey('s'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down', 'down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    MoveSequence(directions=['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'down'], delay_per_step=0.008),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),
    PressKey('c'),

    Pause(1.0),
    Comment("Drawing complete!"),
]

SPEED_MULTIPLIER = 83.3650
