"""Bake the video-guide QR matrix into purple_tui/qr_data.py.

Dev-time only: the `qrcode` package is NOT a runtime dependency. Purple ships
the pre-computed matrix so the Help screen renders it with no import cost. Keep
the URL and error-correction level in sync with landing/scripts/generate-qr.sh.

Usage:
    just python scripts/gen_video_qr.py
"""

from pathlib import Path

import qrcode
from qrcode.constants import ERROR_CORRECT_H

VIDEO_URL = "https://purplecomputer.org/video"
OUT = Path(__file__).resolve().parent.parent / "purple_tui" / "qr_data.py"


def main() -> None:
    qr = qrcode.QRCode(error_correction=ERROR_CORRECT_H, border=2)
    qr.add_data(VIDEO_URL)
    qr.make(fit=True)
    rows = ["".join("1" if cell else "0" for cell in row) for row in qr.get_matrix()]

    body = ",\n".join(f'    "{r}"' for r in rows)
    OUT.write_text(
        '"""Generated by scripts/gen_video_qr.py. Do not edit by hand."""\n\n'
        f'VIDEO_QR_URL = "{VIDEO_URL}"\n\n'
        "# Each string is one QR module row, including the quiet-zone border.\n"
        "VIDEO_QR_MATRIX = [\n"
        f"{body},\n"
        "]\n"
    )
    print(f"Wrote {OUT} ({len(rows)}x{len(rows)} modules) for {VIDEO_URL}")


if __name__ == "__main__":
    main()
