#!/usr/bin/env python3
"""Convert a photo into Art room paint ops.

Downsamples the photo to canvas cells (cells are twice as tall as wide) and
emits one (x, y, "#rrggbb") paint op per cell, written as a generated data
module plus a PNG preview of the expected canvas.

Usage:
    just python tools/photo_to_art.py PHOTO [--out purple_tui/secret_photo.py]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PIL import Image

from purple_tui.rooms.art_room import COLS as CANVAS_WIDTH, ROWS as CANVAS_HEIGHT, CANVAS_BG as DEFAULT_BG_DARK

CELL_ASPECT = 2  # a canvas cell is twice as tall as it is wide
PREVIEW_CELL_PX = 10


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def fit_to_canvas(width: int, height: int) -> tuple[int, int]:
    """Cell grid size that fits the canvas while preserving the photo aspect."""
    scale = min(CANVAS_WIDTH / width, CANVAS_HEIGHT * CELL_ASPECT / height)
    cols = max(1, round(width * scale))
    rows = max(1, round(height * scale / CELL_ASPECT))
    return cols, rows


def convert(photo_path: str) -> tuple[list[tuple[int, int, str]], list[list[str]]]:
    """Return paint ops and the per-cell hex grid (for the preview render)."""
    image = Image.open(photo_path).convert("RGB")
    cols, rows = fit_to_canvas(*image.size)
    small = image.resize((cols, rows), Image.LANCZOS)
    x0 = (CANVAS_WIDTH - cols) // 2
    y0 = (CANVAS_HEIGHT - rows) // 2

    ops: list[tuple[int, int, str]] = []
    cells: list[list[str]] = []
    for cy in range(rows):
        row_hex: list[str] = []
        for cx in range(cols):
            hex_color = "#{:02x}{:02x}{:02x}".format(*small.getpixel((cx, cy)))
            row_hex.append(hex_color)
            ops.append((x0 + cx, y0 + cy, hex_color))
        cells.append(row_hex)
    return ops, cells


def write_module(ops: list[tuple[int, int, str]], out_path: str, photo_name: str) -> None:
    lines = [
        f'"""Photo {photo_name} as Art room paint ops.',
        "",
        "Generated by tools/photo_to_art.py; do not edit by hand.",
        '"""',
        "",
        "OPS: list[tuple[int, int, str]] = [",
    ]
    for i in range(0, len(ops), 6):
        chunk = ", ".join(repr(op) for op in ops[i:i + 6])
        lines.append(f"    {chunk},")
    lines.append("]")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


def write_preview(cells: list[list[str]], preview_path: str) -> None:
    cell_w, cell_h = PREVIEW_CELL_PX, PREVIEW_CELL_PX * CELL_ASPECT
    image = Image.new(
        "RGB", (CANVAS_WIDTH * cell_w, CANVAS_HEIGHT * cell_h),
        _hex_to_rgb(DEFAULT_BG_DARK),
    )
    x0 = (CANVAS_WIDTH - len(cells[0])) // 2
    y0 = (CANVAS_HEIGHT - len(cells)) // 2
    for cy, row in enumerate(cells):
        for cx, hex_color in enumerate(row):
            image.paste(
                _hex_to_rgb(hex_color),
                ((x0 + cx) * cell_w, (y0 + cy) * cell_h,
                 (x0 + cx + 1) * cell_w, (y0 + cy + 1) * cell_h),
            )
    image.save(preview_path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("photo")
    parser.add_argument("--out", default="purple_tui/secret_photo.py")
    parser.add_argument("--preview", default="/tmp/screenshots/photo_to_art_preview.png")
    args = parser.parse_args()

    ops, cells = convert(args.photo)
    write_module(ops, args.out, os.path.basename(args.photo))
    os.makedirs(os.path.dirname(args.preview), exist_ok=True)
    write_preview(cells, args.preview)
    print(f"{len(ops)} ops ({len(cells[0])}x{len(cells)} cells) -> {args.out}")
    print(f"preview: {args.preview}")


if __name__ == "__main__":
    main()
